name: Unit Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-13

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm run test
